// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMe0DetUDP92s1m4_tkqXHzrxSRMrvoWc',
    appId: '1:786488784664:web:5c3c82b52c7ba96b56906d',
    messagingSenderId: '786488784664',
    projectId: 'nevi-virtual-assistant',
    authDomain: 'nevi-virtual-assistant.firebaseapp.com',
    storageBucket: 'nevi-virtual-assistant.appspot.com',
    measurementId: 'G-3XJ29ZJWGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNi6HFZ76TNz50NH1bzli0H5A09oFtEw8',
    appId: '1:786488784664:android:b1f1c8545342a14056906d',
    messagingSenderId: '786488784664',
    projectId: 'nevi-virtual-assistant',
    storageBucket: 'nevi-virtual-assistant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjrdqVoE-PPz75eR_vbOQrDoZIPixgK9E',
    appId: '1:786488784664:ios:a8fa3fd9f216156856906d',
    messagingSenderId: '786488784664',
    projectId: 'nevi-virtual-assistant',
    storageBucket: 'nevi-virtual-assistant.appspot.com',
    androidClientId: '786488784664-dm4p1f3hssh34v76r9f7sgjendpuh62h.apps.googleusercontent.com',
    iosClientId: '786488784664-46o5fhs3lek744h5ntjvgm1hgbqvioeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.nevilai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjrdqVoE-PPz75eR_vbOQrDoZIPixgK9E',
    appId: '1:786488784664:ios:a8fa3fd9f216156856906d',
    messagingSenderId: '786488784664',
    projectId: 'nevi-virtual-assistant',
    storageBucket: 'nevi-virtual-assistant.appspot.com',
    androidClientId: '786488784664-dm4p1f3hssh34v76r9f7sgjendpuh62h.apps.googleusercontent.com',
    iosClientId: '786488784664-46o5fhs3lek744h5ntjvgm1hgbqvioeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.nevilai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMe0DetUDP92s1m4_tkqXHzrxSRMrvoWc',
    appId: '1:786488784664:web:ae7b4a353da7850756906d',
    messagingSenderId: '786488784664',
    projectId: 'nevi-virtual-assistant',
    authDomain: 'nevi-virtual-assistant.firebaseapp.com',
    storageBucket: 'nevi-virtual-assistant.appspot.com',
    measurementId: 'G-51XFV8G6GF',
  );
}
