import 'package:flutter/material.dart';
class MyAppThemes{
static final lightColorScheme = ThemeData.from(colorScheme: const ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF6E4DA1),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFECDCFF),
  onPrimaryContainer: Color(0xFF280057),
  secondary: Color(0xFF645A70),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFEADEF7),
  onSecondaryContainer: Color(0xFF1F182A),
  tertiary: Color(0xFF7F525C),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFFD9DF),
  onTertiaryContainer: Color(0xFF32101A),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF1D1B1E),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF1D1B1E),
  surfaceVariant: Color(0xFFE8E0EB),
  onSurfaceVariant: Color(0xFF49454E),
  outline: Color(0xFF7B757F),
  onInverseSurface: Color(0xFFF5EFF4),
  inverseSurface: Color(0xFF323033),
  inversePrimary: Color(0xFFD6BAFF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF6E4DA1),
  outlineVariant: Color(0xFFCBC4CF),
  scrim: Color(0xFF000000),
)
);

static final darkColorScheme = ThemeData.from( colorScheme: const ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFD6BAFF),
  onPrimary: Color(0xFF3E1C6F),
  primaryContainer: Color(0xFF553587),
  onPrimaryContainer: Color(0xFFECDCFF),
  secondary: Color(0xFFCEC2DB),
  onSecondary: Color(0xFF352D40),
  secondaryContainer: Color(0xFF4C4357),
  onSecondaryContainer: Color(0xFFEADEF7),
  tertiary: Color(0xFFF1B7C3),
  onTertiary: Color(0xFF4B252E),
  tertiaryContainer: Color(0xFF643B44),
  onTertiaryContainer: Color(0xFFFFD9DF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1D1B1E),
  onBackground: Color(0xFFE7E1E6),
  surface: Color(0xFF1D1B1E),
  onSurface: Color(0xFFE7E1E6),
  surfaceVariant: Color(0xFF49454E),
  onSurfaceVariant: Color(0xFFCBC4CF),
  outline: Color(0xFF958E99),
  onInverseSurface: Color(0xFF1D1B1E),
  inverseSurface: Color(0xFFE7E1E6),
  inversePrimary: Color(0xFF6E4DA1),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFD6BAFF),
  outlineVariant: Color(0xFF49454E),
  scrim: Color(0xFF000000),
)
);

}
